default_platform(:android)

platform :android do
  desc "validate"
  lane :validate do
    validate_play_store_json_key
  end

  desc "download"
  lane :download do
    download_from_play_store
  end
end
